### PR TITLE
PHP 8.1 compatibility

### PR DESCRIPTION
**Pull request by marcel-mathias-nolte**
tested on Contao 4.13

### CODE REVIEW

**Comment by trilobit-gmbh** [comment]
Thank you for the pull request. I'll look at this earlier in the week; also with php7.3, php7.4 and Contao 4.9. After that I can safely merge it. ;-)

**Comment by qzminski** [comment]
@trilobit-gmbh when do you plan to merge this one? :wink:

**Comment by trilobit-gmbh** [comment]
i have to fix some php8 isses like "Non-static method Trilobit\TilesBundle\Tiles::generateTiles() cannot be called statically"

**Comment by trilobit-gmbh** [comment]
Thanks ;-) Some other updates on pull/7

**Pull request merged**
